version: "1" 

services:      
   mysql_db:
      image: mysql
      container_name: MYSQL
      ports:
         - 3306:3306
      environment:
         MYSQL_ROOT_PASSWORD: "admin"
      volumes:
         - ./volumen/mysql_db:/var/lib/mysql
  





